### ISSUE TITLE
New cgroup memory.memsw limit not applied on profile change, requires restart

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxcfs#439]
As this is further to https://github.com/lxc/lxcfs/issues/434 as a direct result of my testing on the latest LXD 4.8 I am posting this here, despite this exact undesirable behavior probably belongs over in LXD? Also, this may be "expected" behavior as it relates to cgroup limits set with raw.lxc - but to me that doesn't seem correct and in case it is not, I am posting this report of my findings.

In any case, given two profiles, say:

```
# lxc profile show profileone
config:
  limits.memory: 2GB
  limits.memory.enforce: hard
  limits.memory.swap: "true"
  raw.lxc: lxc.cgroup.memory.memsw.limit_in_bytes = 10G
description: ""
devices:
  root:
    path: /
    pool: lxd
    size: 5GB
    type: disk
name: profileone
used_by: []

# lxc profile show profiletwo
config:
  limits.memory: 4GB
  limits.memory.enforce: hard
  limits.memory.swap: "true"
  raw.lxc: lxc.cgroup.memory.memsw.limit_in_bytes = 10G
description: ""
devices:
  root:
    path: /
    pool: lxd
    size: 5GB
    type: disk
name: profiletwo
used_by: []
```

Launch a container and inspect memory/swap availability:

```
# lxc launch ubuntu:focal testswaplimits --profile profileone
# lxc exec testswaplimits -- grep SwapTotal /proc/meminfo
SwapTotal:      10485760 kB
```

Change profile and check memory/swap availability again:

```
# lxc profile apply testswaplimits profiletwo
# lxc exec testswaplimits -- grep SwapTotal /proc/meminfo
SwapTotal:       3906248 kB
```

Now this would not be such an issue if this was merely cosmetic, but if we try and run e.g. `stress --vm 4 --vm-bytes 2G` we see that the OOM killer now steps in immediately and kills the process trying to grab memory beyond the RAM allowance, whereas before the profile change it was allowed to use SWAP and was not killed.

This means that a profile change in this case requires a reboot if you want to maintain access to SWAP space in the container, regardless of what your limits were or are being set to.

It does not matter if you are setting a different value in lxc.cgroup.memory.memsw.limit_in_bytes or keeping it the same as is shown above - the limit for available mem+swap always "resets" to effectively 0
