### ISSUE TITLE
[problem] /proc/loadavg does not take effect

### ISSUE THREAD

**Issue by kanghuzai** [lxc/lxcfs#578]
# System info
```
liunx: 3.10.0-957.el7.x86_64
lxcfs: 5.0.2
```
# Kubelet config
node enable cpuManager and nuam
```
# cat /var/lib/kubelet/cpu_manager_state 
{"policyName":"static","defaultCpuSet":"0-1,3-13,15-23","entries":{"f22d1adb-1dec-4539-bb8f-36ee4becacf9":{"member-admin-app":"2,14"}},"checksum":2269792505}
```
# Pod config
```
spec:
      volumes:
        - name: proc-cpuinfo
          hostPath:
            path: /var/lib/lxcfs/proc/cpuinfo
            type: ''
        - name: proc-diskstats
          hostPath:
            path: /var/lib/lxcfs/proc/diskstats
            type: ''
        - name: proc-meminfo
          hostPath:
            path: /var/lib/lxcfs/proc/meminfo
            type: ''
        - name: proc-stat
          hostPath:
            path: /var/lib/lxcfs/proc/stat
            type: ''
        - name: proc-swaps
          hostPath:
            path: /var/lib/lxcfs/proc/swaps
            type: ''
        - name: proc-uptime
          hostPath:
            path: /var/lib/lxcfs/proc/uptime
            type: ''
        - name: proc-slabinfo
          hostPath:
            path: /var/lib/lxcfs/proc/slabinfo
            type: ''
        - name: cpu-online
          hostPath:
            path: /var/lib/lxcfs/sys/devices/system/cpu/online
            type: ''
        - name: proc-loadavg
          hostPath:
            path: /var/lib/lxcfs/proc/loadavg
            type: ''
      containers:
        - name: member-admin-app
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - name: proc-cpuinfo
              mountPath: /proc/cpuinfo
            - name: proc-diskstats
              mountPath: /proc/diskstats
            - name: proc-meminfo
              mountPath: /proc/meminfo
            - name: proc-stat
              mountPath: /proc/stat
            - name: proc-swaps
              mountPath: /proc/swaps
            - name: proc-uptime
              mountPath: /proc/uptime
            - name: proc-slabinfo
              mountPath: /proc/slabinfo
            - name: cpu-online
              mountPath: /sys/devices/system/cpu/online
            - name: proc-loadavg
              mountPath: /proc/loadavg
```

# Pod exec result
```
top - 15:43:10 up  6:11,  0 users,  load average: 5.89, 5.39, 6.54
Tasks:   9 total,   1 running,   7 sleeping,   0 stopped,   1 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  1.8 us,  1.8 sy,  0.0 ni, 96.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,  1108932 free,   843836 used,   144384 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1253316 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                         
    1 root      20   0    4400    404    280 S   0.0  0.0   0:00.51 tini                                                                                                            
    8 root      20   0 3206976 728884  24848 S   0.0 34.8   4:46.59 java                                                                                                            
   55 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 sh                                                                                                              
  147 root      20   0 2545556 154868  20096 S   0.0  7.4   0:35.28 java                                                                                                            
  225 root      20   0   15568   2232   1504 S   0.0  0.1   0:00.08 sh                                                                                                              
  243 root      20   0   15568   2180   1456 S   0.0  0.1   0:00.08 sh                                                                                                              
  265 root      20   0   15568   2228   1504 S   0.0  0.1   0:00.02 sh                                                                                                              
  273 root      20   0   15568   2036   1384 S   0.0  0.1   0:00.02 sh                                                                                                              
  280 root      20   0   59656   2136   1508 R   0.0  0.1   0:00.00 top
```
# Node exec result
```
top - 15:43:11 up 18:21,  2 users,  load average: 5.89, 5.39, 6.54
Tasks: 946 total,   3 running, 925 sleeping,   0 stopped,  18 zombie
%Cpu0  : 28.4 us,  3.8 sy,  0.0 ni, 66.8 id,  0.0 wa,  0.0 hi,  1.0 si,  0.0 st
%Cpu1  : 25.4 us,  3.7 sy,  0.0 ni, 69.2 id,  1.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu2  :  3.4 us,  2.0 sy,  0.0 ni, 93.9 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu3  : 23.9 us,  2.7 sy,  0.0 ni, 73.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  : 27.4 us,  3.3 sy,  0.0 ni, 68.6 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu5  : 35.5 us,  6.4 sy,  0.0 ni, 55.5 id,  2.3 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu6  : 42.0 us,  2.7 sy,  0.0 ni, 55.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  : 28.1 us,  6.4 sy,  0.0 ni, 64.5 id,  0.3 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu8  : 33.4 us,  4.3 sy,  0.0 ni, 61.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu9  : 25.2 us,  4.0 sy,  0.0 ni, 67.5 id,  3.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu10 : 45.2 us,  2.3 sy,  0.0 ni, 51.5 id,  0.0 wa,  0.0 hi,  1.0 si,  0.0 st
%Cpu11 : 12.8 us,  4.4 sy,  0.0 ni, 80.1 id,  2.7 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu12 : 19.7 us,  2.0 sy,  0.0 ni, 77.7 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu13 : 22.3 us,  5.3 sy,  0.0 ni, 72.1 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu14 :  2.7 us,  1.7 sy,  0.0 ni, 95.0 id,  0.3 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu15 : 42.9 us,  4.0 sy,  0.0 ni, 52.8 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu16 : 15.0 us,  2.0 sy,  0.0 ni, 82.1 id,  0.0 wa,  0.0 hi,  1.0 si,  0.0 st
%Cpu17 :  4.7 us,  1.3 sy,  0.0 ni, 94.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu18 : 24.3 us,  1.7 sy,  0.0 ni, 73.3 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
%Cpu19 : 17.7 us,  3.7 sy,  0.0 ni, 77.7 id,  1.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu20 :  6.3 us,  2.3 sy,  0.0 ni, 91.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu21 : 10.6 us,  2.6 sy,  0.0 ni, 86.4 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu22 :  8.3 us,  2.3 sy,  0.0 ni, 89.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu23 :  5.6 us,  1.7 sy,  0.0 ni, 89.0 id,  3.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13181204+total, 82838352 free, 21958700 used, 27014988 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 10855417+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                         
45572 root      20   0   11.3g   1.1g  29696 S 154.5  0.9 492:39.29 java                                                                                                            
33816 root      20   0 1245936 160272  13984 R 150.5  0.1   0:08.43 node                                                                                                            
33331 root      20   0 1214856 397824  14572 R 125.7  0.3   0:20.72 npm                                                                                                             
10019 root      20   0   14.8g 759944  23368 S  22.1  0.6 573:56.15 dockerd                                                                                                         
12862 root      20   0   13.6g   1.0g  30876 S  22.1  0.8   6:08.11 java                                                                                                            
21308 root      20   0   13.9g   1.1g  27476 S  20.8  0.9  53:17.68 java                                                                                                            
23050 root      20   0 8209584 834544  26416 S  19.1  0.6   2:51.80 java                                                                                                            
45142 root      20   0 2431868 133352  37636 S  11.2  0.1  25:56.16 kubelet
```

# The docker example is also not the expected result
```
docker run -it -m 256m --memory-swap 256m --cpuset-cpus "0,2" \
      -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
      -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw \
      -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw \
      -v /var/lib/lxcfs/proc/stat:/proc/stat:rw \
      -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw \
      -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw \
      -v /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw \
      -v /var/lib/lxcfs/proc/loadavg:/proc/loadavg:rw \
      -v /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw \
      ubuntu:18.04 /bin/bash
```
