### ISSUE TITLE
System in container can take CPUs on host offline

### ISSUE THREAD

**Issue by niansa** [lxc/lxcfs#629]
# Required information

 * Distribution: Debian
 * Distribution version: Bookworm
 * The output of "incus info": [incus-log.txt](https://github.com/lxc/incus/files/14599478/incus-log.txt)

# Issue description

Apparently the system in the container is able to take CPUs on the host offline/back online by writing to `/sys/devices/system/cpu/cpu*/online`

# Steps to reproduce

 1. Create a Ubuntu 24.04 (for example) instance
 2. Open a shell in the instance
 4. `cd` to `/sys/devices/system/cpu/cpu0/`
 5. As root, write `0` into the file `online`
 6. Log out of the shell
 7. Check `htop` or any other tool and you'll see the core is offline on the host system

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`incus info NAME --show-log`)
 - [x] Container configuration (`incus config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the 

```
[6669597.241904] smpboot: CPU 1 is now offline
```
```
Name: ubuntu
Status: RUNNING
Type: container
Architecture: x86_64
PID: 3742945
Created: 2024/03/14 09:18 CET
Last Used: 2024/03/14 09:27 CET

Resources:
  Processes: 14
  CPU usage:
    CPU usage (in seconds): 11
  Memory usage:
    Memory (current): 307.64MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: veth53b86c1b
      MAC address: 00:16:3e:13:72:ee
      MTU: 1500
      Bytes received: 58.28MB
      Bytes sent: 5.81MB
      Packets received: 40871
      Packets sent: 22334
      IP addresses:
        inet:  10.41.89.171/24 (global)
        inet6: fd42:97dc:6ffa:abeb:216:3eff:fe13:72ee/64 (global)
        inet6: fe80::216:3eff:fe13:72ee/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 5.79kB
      Bytes sent: 5.79kB
      Packets received: 44
      Packets sent: 44
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:


```
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu noble amd64 (20240313_07:42)
  image.os: Ubuntu
  image.release: noble
  image.requirements.cgroup: v2
  image.serial: "20240313_07:42"
  image.type: squashfs
  image.variant: default
  limits.cpu: 10-17
  limits.cpu.priority: "3"
  limits.memory: 8GiB
  limits.processes: "5120"
  volatile.base_image: 2699b561cdee3145a56b8a990965456f7524febb37473994618c9d2fb56aaf6c
  volatile.cloud-init.instance-id: ddfb179d-3369-4e20-bacf-f0bdf3b93ff7
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.incubr0.host_name: veth53b86c1b
  volatile.incubr0.hwaddr: 00:16:3e:13:72:ee
  volatile.incubr0.name: eth0
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 9c72b2c7-9129-4c8d-acdf-02c652d4e312
  volatile.uuid.generation: 9c72b2c7-9129-4c8d-acdf-02c652d4e312
devices:
  incubr0:
    limits.egress: 500Mbit
    limits.ingress: 500Mbit
    nictype: bridged
    parent: incubr0
    type: nic
  root:
    path: /
    pool: hdd
    type: disk
ephemeral: false
profiles:
- restricted
stateful: false
description: ""
```
```
time="2024-03-14T08:22:12+01:00" level=warning msg="AppArmor support has been disabled because of lack of kernel support"
time="2024-03-14T08:22:12+01:00" level=warning msg=" - AppArmor support has been disabled, Disabled because of lack of kernel support"
time="2024-03-14T08:56:18+01:00" level=warning msg="IPv4 bridge netfilter not enabled. Instances using the bridge will not be able to connect to the forward listen IPs" driver=bridge err="br_netfilter kernel module not loaded" network=incubr0 project=default
time="2024-03-14T08:56:31+01:00" level=warning msg="IPv4 bridge netfilter not enabled. Instances using the bridge will not be able to connect to the forward listen IPs" driver=bridge err="br_netfilter kernel module not loaded" network=incubr0 project=default
time="2024-03-14T09:00:49+01:00" level=warning msg="IPv4 bridge netfilter not enabled. Instances using the bridge will not be able to connect to the forward listen IPs" driver=bridge err="br_netfilter kernel module not loaded" network=incubr0 project=default
time="2024-03-14T09:09:06+01:00" level=warning msg="The backing filesystem doesn't support quotas, skipping set quota" driver=dir path=/var/lib/incus/storage-pools/hdd/containers/ubuntu pool=hdd size=12000000000 volID=1
```
